      # =========================================================
      # WEB
      # =========================================================

      - name: Prune Web application
        run: |
          rm -rf out
          pnpm turbo prune web --docker

      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            buildwithamit/bms-web:${{ github.sha }}
            buildwithamit/bms-web:latest

      # =========================================================
      # HTTP SERVER
      # =========================================================

      - name: Prune HTTP server
        run: |
          rm -rf out
          pnpm turbo prune http-server --docker

      - name: Build and push HTTP image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/http-server/Dockerfile
          push: true
          tags: |
            buildwithamit/bms-http-server:${{ github.sha }}
            buildwithamit/bms-http-server:latest

      # =========================================================
      # WEBSOCKET SERVER
      # =========================================================

      - name: Prune WebSocket server
        run: |
          rm -rf out
          pnpm turbo prune ws-server --docker

      - name: Build and push WebSocket image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/ws-server/Dockerfile
          push: true
          tags: |
            buildwithamit/bms-ws-server:${{ github.sha }}
            buildwithamit/bms-ws-server:latest